spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    #url: jdbc:postgresql://postgres-jcnn.railway.internal:5432/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
